import com.github.spotbugs.snom.SpotBugsTask

plugins {
    java
    checkstyle
    id("com.github.spotbugs")
    id("com.diffplug.spotless")
    id("com.google.protobuf") version "0.9.2"
}

dependencies {
    implementation("com.google.protobuf:protobuf-java:3.21.12")
}

// Exclude classes generated by protoc from Checkstyle and Spotbugs:
val excludePattern = "specmesh/examples/schema_demo/model"
tasks.withType<SpotBugsTask> {
    classes = classes.filter {
        !it.path.contains(excludePattern)
    }
}
tasks.withType<Checkstyle> {
    exclude("**/$excludePattern*")
}
spotless {
    java {
        targetExclude("**/generated/source*/**/*.*")
    }
}